network:
  name: resnet18
  input_shape:
    width: 128
    height: 128
    channels: 1
  preview_shape: 32

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  #fine_tune_from: 'resnet-18_40-epochs'
  fine_tune_from: None
  pretrained_weights: false

  projection_head:
    mlp_hidden_size: 512
    projection_size: 128

dataset: cutout_factor2.5/meerkat

trainer:
  batch_size: 256
  m: 0.996 # momentum update
  checkpoint_interval: 500000
  max_epochs: 3
  num_workers: 8

optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004