network:
  name: resnet18
  input_shape:
    width: 128
    height: 128
    channels: 3

  preview_shape: 81
  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  #fine_tune_from: 'resnet-18_40-epochs'
  fine_tune_from: None
  pretrained_weights: false

  projection_head:
    mlp_hidden_size: 1024
    projection_size: 512

dataset: 4-HULK

trainer:
  batch_size: 254
  m: 0.996 # momentum update
  checkpoint_interval: 500000
  max_epochs: 10
  num_workers: 8

optimizer:
  params:
    lr: 0.003
    momentum: 0.9
    weight_decay: 0.0004