dataset: 3_channel_croppedbackyard

method: byol

network:
  name: resnet18

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  #fine_tune_from: 'resnet-18_40-epochs'
  fine_tune_from: None

  projection_head:
    mlp_hidden_size: 512
    projection_size: 128

data_transform:
  normalization: min_max # sigma, multi,
  rotate: 45
  pad_shift: True
  flip_X: True
  flip_Y: True
  input_shape: same

trainer:
  batch_size: 128
  m: 0.996 # momentum update
  checkpoint_interval: 500000
  max_epochs: 1500
  num_workers: 8 # auto?

optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004
