network:
  name: resnet18
  input_shape:
    width: 128
    height: 128
    channels: 3

  preview_shape: 32
  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  #fine_tune_from: 'logs/test/test4/best_model.pt'
  fine_tune_from: None
  pretrained_weights: True
  projection_head:
    mlp_hidden_size: 1024
    projection_size: 512

dataset: 1-ZORRO/data

trainer:
  batch_size: 512
  m: 0.996 # momentum update
  checkpoint_interval: 500000
  max_epochs: 100
  num_workers: 8

optimizer:
  params:
    lr: 0.007
    momentum: 0.9
    weight_decay: 0.0004